micronaut:
  application:
    name: hello-backend

dynamodb:
  table-name: hello

test-resources:
  containers:
    dynamodb:
      image-name: amazon/dynamodb-local
      hostnames:
        - dynamodb-local.host
      exposed-ports:
        - dynamodb-local.port: 8000

#dynamodb-local:
#  host: localhost
#  port: 50157
